### PR TITLE
contribute code

### PR DESCRIPTION
**Pull request by nybbs2003**

### CODE REVIEW

**Comment by sublimator** [comment]
Thanks! I will take a look at this over the next few days.  

I might end up having to just cherry pick some of the changes, as the diff is very noisy due to using tabs where before it was spaces.  Travis also failed due to `java.lang.NoClassDefFoundError: org/eclipse/aether/spi/connector/Transfer$State`

I noticed that the newer versions of org.json doesn't use checked exceptions as base class for JSONException any more. That is kind of nice, considering they tend to just get wrapped in RuntimeException a lot of the time.

**Comment by sublimator** [comment]
I prepared [a branch](https://github.com/ripple/ripple-lib-java/commits/master-next) with some local changes, including yours which I rebased/squashed.

See a5ec130f24b2fd4af652a9c7b22b4393d4146205 and d990b718787dcbe5eed4715f3a6f5970024d06a5

Note in subsequent commits I had to roll back the org.json version to the version prior to what you set, due to byte code compat issues. I also removed some methods like `submit` which assumed payment.  But the majority of your contributions are intact :)

I wanted to give credit, but there was some noisy changes, so decided to squash:
* Using tabs instead of spaces
* Changing then restoring eclipse files

I can either recommit showing the author as me, or leave it as is, if you're happy with that.

**Comment by sublimator** [comment]
To be clear the JSONException issue is still fixed in `20140107` :)

**Comment by nybbs2003** [comment]
It it fine to recommit the code. :)

**Comment by sublimator** [comment]
Ok then :) I need to give this branch a bit of testing, then I'll make it
master some time over next few days.

**Pull request closed without merging**
