### PR TITLE
Removed unused imports in non-test code

### PR DESCRIPTION
**Pull request by p-**
Hi there
I removed some unused imports to reduce the number of warnings.

### CODE REVIEW

**Comment by sublimator** [comment]
Travis says: `Exception in thread "main" java.lang.NoClassDefFoundError: org/eclipse/aether/spi/connector/Transfer$State`

Will look later, thanks!

**Comment by p-** [comment]
The Travis error seems unrelated to this pull request. Might be related to the maven version in use on Travis CI. I can reproduce it with maven 3.2.5, but not with 3.2.3.

**Comment by sublimator** [comment]
Yeah, it's weird huh.

Just I couldn't use Travis to tell if the patch was correct.

I'll need to look at it locally.

**Comment by sublimator** [comment]
It's in here: https://github.com/ripple/ripple-lib-java/commits/master-next

**Pull request closed without merging**
